sudo: required
dist: bionic
language: go
go:
- 1.12.5
services:
- docker
eploy:
  provider: releases
  api_key:
    secure: "CfxVi+E62pT/DfQZoyH7FHiZS8JYYcxbAD6gLDv9SqtcAfPXWPZhOX01KJhN+vGuIm0WR9ZoPHC862NgGC0RuN7ljlzRbxYlzCN6QwvVogNfipxgYDOMr7HMbdPuM8+SW434wW54vyEdkb+cTH3/8+Ht7pGBvZ7ie31X3J21Hcs4oChQqJc3uhYmP/fYQg7e4xmkt4GAfaTNsv5oXlVfsTulNqHzRxrj1eoPv89NpoMmoP5IzB3fhJucx87IVaR80CTB3SBEGM/tCRVkXF/pYWYTkFi8nUmdGeucY++5oYfH2e8vybfjQdkNt1r1E3s80bX8aYMzaFgnK1d5wO1wlGtI8N/ps80kPyE97hWmUTIdRyWfVSZr4MimMFwsXdb+m1CqwN31LzdyGknxGqmj2g10mriW+rL5ZCXP8VD541DrBClhcpk3dfeGNAuFX4yhZyB456y/gviac7ue8aUCrty4E5DBo40FOk6jaDoFRKyGKjyXNSas1tgav+txD7M0mOyOEXBbjoT2WMyKrQFzt3EFgVpwuiUIJeMsShnAyyx24QWg0PclZUisHKhkJZ5NO+W/oIuBH4a0KpDGY4ABD3kgptNaykhiChJGi0uqRU65zOyH68LJ8dFn5lPgwnuxZZqRyYNcZfmFN9LuO4dD2mOskGMJMBM4jWcVJ+gGlDs="
  on:
    tags: true
  file: "./build/khostdns"
  skip_cleanup: true
env:
  global:
  - GO111MODULE=on
  - secure: "eP1t/OIlb1eqt+Z1nYX7flb6WU7xWHw8OXVme1tsZN33CS6cLMm3SbhUMg9EV03+8ErytxTXTz1LuCXmCm30QfLIM5ovEasB+0XSH1gqukf5Pkd+SK8QCi80rOIP35ZZNDc3an9/9mJMxANc7NcdohpMvO5kBPv7PGD/S0DCXfgz9cqO/4CfD+MtxJRuCG9OZtOlp7m7Bw5J9/uIBCnBifNp9KLzlD3R88slN2gNI7IX4lqJFVoNdYG9f+xNWxHWo3vP/BQ5RLTbXWMjJCq/NQEOL+nH437LGwaWK9zHxPep6r71IYJfBbwEQyw999j+J3IALNb2qVbu1Y7g3k/cioiCRVoZrNsGBCiR06fJFX6z8ue/tMsyt9Y7f17PgdKKR+xcOumu0MU6AmyHX89CsKeHF5GksEjPLlqBVR2TWrLBjPM49eR7jrp5Vy+TXFWOEJ4+S6eY/E0vIXiFgjnVzYJK4FUCLsS72FZgaJvfZDoGVvTdb3CH33RZVBVduO20sBFkoISrf/NKFRA0iOF2J0xd86VXkvZvuuRZ0cNsKimrbgNIfvOYtM4bjJp3nmHQrwLy3zLCSkfbsYqpnSo2ip5DgPRzSTl7d4KKUIf5LTbWhzi+ereLKai0fynPbERKMbn2tlgYKSU5lbYFvUuVIjEgRuwI9CVie1HcQiLrAEw="
  - secure: "ZC0nuxi4biLzJ+sjTK42ACxyqHWi970xXKhDh/03o8VY3iaPfcInh+K1PUhrqVw9IwIqsdexJpy8csNBjbw3AN45JHsgoXTXUn9XAAfdz66ns2I+ttBeqByDJ6lGynORxAS/fS0PzFtoRZy+lSc2zlJ6gRjATmlHGJCNy0ITHpR+pgtQGf0MEtyMPArBWRTGfPPj2y7VidrxeC4VCo5P3hKgT1CeknzO5bov7aeo26xQqqenl+GY7ycjFgVBpngxT9gxKlTTzsNqrK+jpih3ZGMOKZ3OOtY7lCrT1uXSR3iqFhu0fyHBUCQ30syDpUi5pxX0QgTbqH+wxpQP9ivPePXNY6QMHBZmUfYd+N57gbS5OvQLrjhpPA8QL+1wtue6JNKEH/mF4cXki1j+6QPFQAYTb5KTN+sWm8eHLBwkA/Hv0neDh2dnkUSWetqYpFhr4BPdNjDwbvm2uPmdKo3d1awA2uvYuK2O6CqMgjngRyPeY/tROia5/8VtxXZS37DaICMmdPSubPqioL5/gXJOL8/2yI8JVsth4crzh5pJjLcO05ah17zVHbEUzi436Q5oFuAf/YYQcoTFDrkWGLXrRoDQngY0lT/tCuW3SsaG8PCekrUN8x1owqxQ1JqqNeol1fnco8c4cpB/JJhQjc0jiLl/zeMNmsVBlrkpo2IWwSs="
script:
- "./dockerBuild.sh"
